### ISSUE TITLE
simple_kinesis_processor.sh never gets executed

### ISSUE THREAD

**Issue by nedda76** [colinbankier/amazon-kinesis-client-elixir#1]
Hi Colin,

I forked your project and updated the Timex version to 0.19 because of some incompatibilities w elixir 1.x

When running locally, I noticed that the simple kinesis client never executes. Looking at it more closely, it seems like the simple_kinesis_processor.sh never gets executed.

I do see a message:

INFO: Running ElixirKCLSample to process stream roa-dev with executable sample/simple_kinesis_processor.sh 

but nothing happens in terms of the process_records output, altogether it seems like it does not get invoked at all.

Any pointers? Not sure whether you are still maintaining this project.

**Comment by colinbankier** [comment]
Hi,
Here is a sample project that used the library, specifically the GenServer
that starts the client:
https://github.com/colinbankier/pusher/blob/master/lib/pusher/kinesis_client.ex

Hopefully that provides some further insight into how to get it running.

This library is not actively maintained, I am sorry to report. If you're
able to share any updates/enhancements etc that would be fantastic :)

Let me know if I can help further, best of luck!

**Comment by nedda76** [comment]
Hi Colin,

Thanks for the help - I will create a PR for the Timex fixes.
